In [1]:
import os
import pandas as pd
import numpy as np
import zipcode

data_2015 = os.path.join('sb_ca2015_all_csv_v3.txt')
data_2015_df = pd.read_csv(data_2015)

entities_2015 = os.path.join('sb_ca2015entities_csv.txt')
entities_2015_df = pd.read_csv(entities_2015)

data_2016 = os.path.join('sb_ca2016_all_csv_v3.txt')
data_2016_df = pd.read_csv(data_2016)

entities_2016 = os.path.join('sb_ca2016entities_csv.txt')
#entities_2016_df = pd.read_csv(entities_2016)

data_2017 = os.path.join('sb_ca2017_all_csv_v2.txt')
data_2017_df = pd.read_csv(data_2017)

entities_2017 = os.path.join('sb_ca2017entities_csv.txt')
#entities_2017_df = pd.read_csv(entities_2017)

subgroups = os.path.join('Subgroups.txt')
subgroups_df = pd.read_csv(subgroups, header=None)

tests = os.path.join('Tests.txt')
tests_df = pd.read_csv(tests)

#data_2015_df.head()
tests_df.head()

   Test Id  Test ID Num                             Test Name
0        1            1   SB - English Language Arts/Literacy
1        2            2                      SB - Mathematics
2        3            3  CAA - English Language Arts/Literacy
3        4            4                     CAA - Mathematics

In [2]:
#subgroups_df.head()

In [3]:
#data_2015_df.shape

In [4]:
#data_2016_df.shape

In [5]:
#data_2017_df.shape

In [6]:
#list(data_2015_df)

In [7]:
#list(data_2016_df)

In [8]:
#list(data_2017_df)

In [9]:
data = [data_2015_df, data_2016_df, data_2017_df]
data = pd.concat(data)
data.shape

(9584749, 38)

In [10]:
#list(data)

In [11]:
#entities_2015_df.head()

In [12]:
#entities_2015_df.shape

In [13]:
data = data[data['School Code'] != 0]
data = data[data['Subgroup ID'] == 1]
data.shape

(261804, 38)

In [14]:
data = pd.merge(data, entities_2015_df, how='left', on='School Code')

In [15]:
data = data[data['Percentage Standard Exceeded'] != '*']
data = pd.merge(data, tests_df, how='left', on='Test Id')
data.shape

(227204, 49)

In [16]:
data.to_csv("School_Scores_Data.csv", index=False, header=True)

In [17]:
#data_2015_df_group = data_2015_df.groupby('School Code')
#data_2015_df_group.count().head(10)

In [18]:
#school_lookup = data_2015_df.loc[data_2015_df['School Code'] == 100057]
#school_lookup = school_lookup.loc[school_lookup['Subgroup ID'] == 1]
#school_lookup = school_lookup['Grade'].value_counts()
#school_lookup = school_lookup.groupby(['Grade', 'Test Id'])
#school_lookup.head()

In [19]:
data.dtypes

Area 1 Percentage Above Standard          object
Area 1 Percentage At or Near Standard     object
Area 1 Percentage Below Standard          object
Area 1 Percentage Near Standard           object
Area 2 Percentage Above Standard          object
Area 2 Percentage At or Near Standard     object
Area 2 Percentage Below Standard          object
Area 2 Percentage Near Standard           object
Area 3 Percentage Above Standard          object
Area 3 Percentage At or Near Standard     object
Area 3 Percentage Below Standard          object
Area 3 Percentage Near Standard           object
Area 4 Percentage Above Standard          object
Area 4 Percentage At or Near Standard     object
Area 4 Percentage Below Standard          object
Area 4 Percentage Near Standard           object
CAASPP Reported Enrollment                object
County Code_x                              int64
District Code_x                            int64
Filler_x                                 float64
Grade                                      int64
Mean Scale Score                          object
Percentage Standard Exceeded              object
Percentage Standard Met                   object
Percentage Standard Met and Above         object
Percentage Standard Nearly Met            object
Percentage Standard Not Met               object
School Code                                int64
Students Tested                           object
Students with Scores                      object
Subgroup ID                                int64
Test Id                                    int64
Test Type                                 object
Test Year_x                                int64
Total CAASPP Enrollment                  float64
Total Tested At Entity Level              object
Total Tested at Subgroup Level           float64
Total Tested with Scores                  object
County Code_y                            float64
District Code_y                          float64
Filler_y                                 float64
Test Year_y                              float64
Type Id                                  float64
County Name                               object
District Name                             object
School Name                               object
Zip Code                                  object
Test ID Num                                int64
Test Name                                 object
dtype: object

In [20]:
data['Percentage Standard Met and Above'] = data['Percentage Standard Met and Above'].astype(float)
data['Zip Code'] = data['Zip Code'].astype(str)

In [21]:
data.dtypes

Area 1 Percentage Above Standard          object
Area 1 Percentage At or Near Standard     object
Area 1 Percentage Below Standard          object
Area 1 Percentage Near Standard           object
Area 2 Percentage Above Standard          object
Area 2 Percentage At or Near Standard     object
Area 2 Percentage Below Standard          object
Area 2 Percentage Near Standard           object
Area 3 Percentage Above Standard          object
Area 3 Percentage At or Near Standard     object
Area 3 Percentage Below Standard          object
Area 3 Percentage Near Standard           object
Area 4 Percentage Above Standard          object
Area 4 Percentage At or Near Standard     object
Area 4 Percentage Below Standard          object
Area 4 Percentage Near Standard           object
CAASPP Reported Enrollment                object
County Code_x                              int64
District Code_x                            int64
Filler_x                                 float64
Grade                                      int64
Mean Scale Score                          object
Percentage Standard Exceeded              object
Percentage Standard Met                   object
Percentage Standard Met and Above        float64
Percentage Standard Nearly Met            object
Percentage Standard Not Met               object
School Code                                int64
Students Tested                           object
Students with Scores                      object
Subgroup ID                                int64
Test Id                                    int64
Test Type                                 object
Test Year_x                                int64
Total CAASPP Enrollment                  float64
Total Tested At Entity Level              object
Total Tested at Subgroup Level           float64
Total Tested with Scores                  object
County Code_y                            float64
District Code_y                          float64
Filler_y                                 float64
Test Year_y                              float64
Type Id                                  float64
County Name                               object
District Name                             object
School Name                               object
Zip Code                                  object
Test ID Num                                int64
Test Name                                 object
dtype: object

In [22]:
data_summary = data.groupby(['School Name', 'County Name', 'District Name', 'Zip Code', 'Grade', 'Test Name']).agg({'Percentage Standard Met and Above': ['mean']}).rename(columns={'mean': '2015-2017 Avg Percentage Standard Met and Above'})
rounding = lambda x: round(x, 2)
data_summary = data_summary.apply(rounding)
data_summary.columns = data_summary.columns.droplevel()
data_summary = data_summary.reset_index()
data_summary['Test Name'] = data_summary['Test Name'].str[5:]
bins = [0, 6, 9, 14]
group_names = ['Elementary School', 'Middle School', 'High School']
data_summary['School Type'] = pd.cut(data_summary['Grade'], bins, labels = group_names)

zcode = data_summary['Zip Code']
cities = []
for z in zcode:
    try:
        myzip = zipcode.isequal(z)
        cities.append(myzip.city)
    except:
        cities.append("")

data_summary['City'] = cities
data_summary

,School Name,County Name,District Name,Zip Code,Grade,Test Name,2015-2017 Avg Percentage Standard Met and Above,School Type,City
0,21St Century Learning Institute,Riverside,Beaumont Unified,90804,8,English Language Arts/Literacy,45.00,Middle School,LONG BEACH
1,21St Century Learning Institute,Riverside,Beaumont Unified,90804,8,Mathematics,18.00,Middle School,LONG BEACH
2,21St Century Learning Institute,Riverside,Beaumont Unified,90804,11,English Language Arts/Literacy,34.29,High School,LONG BEACH
3,21St Century Learning Institute,Riverside,Beaumont Unified,90804,11,Mathematics,4.38,High School,LONG BEACH
4,21St Century Learning Institute,Riverside,Beaumont Unified,90804,13,English Language Arts/Literacy,33.44,High School,LONG BEACH
5,21St Century Learning Institute,Riverside,Beaumont Unified,90804,13,Mathematics,7.04,High School,LONG BEACH
6,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,3,English Language Arts/Literacy,58.15,Elementary School,CYPRESS
7,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,3,Mathematics,62.73,Elementary School,CYPRESS
8,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,4,English Language Arts/Literacy,70.72,Elementary School,CYPRESS
9,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,4,Mathematics,66.31,Elementary School,CYPRESS
10,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,5,English Language Arts/Literacy,66.41,Elementary School,CYPRESS
11,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,5,Mathematics,53.46,Elementary School,CYPRESS
12,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,6,English Language Arts/Literacy,71.60,Elementary School,CYPRESS
13,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,6,Mathematics,61.97,Elementary School,CYPRESS
14,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,13,English Language Arts/Literacy,67.22,High School,CYPRESS
15,A. E. Arnold Elementary,Orange,Cypress Elementary,90630,13,Mathematics,60.82,High School,CYPRESS
16,A. G. Currie Middle,Orange,Tustin Unified,92780,6,English Language Arts/Literacy,29.17,Elementary School,TUSTIN
17,A. G. Currie Middle,Orange,Tustin Unified,92780,6,Mathematics,15.41,Elementary School,TUSTIN
18,A. G. Currie Middle,Orange,Tustin Unified,92780,7,English Language Arts/Literacy,37.12,Middle School,TUSTIN
19,A. G. Currie Middle,Orange,Tustin Unified,92780,7,Mathematics,22.62,Middle School,TUSTIN
20,A. G. Currie Middle,Orange,Tustin Unified,92780,8,English Language Arts/Literacy,41.35,Middle School,TUSTIN
21,A. G. Currie Middle,Orange,Tustin Unified,92780,8,Mathematics,18.94,Middle School,TUSTIN
22,A. G. Currie Middle,Orange,Tustin Unified,92780,13,English Language Arts/Literacy,35.82,High School,TUSTIN
23,A. G. Currie Middle,Orange,Tustin Unified,92780,13,Mathematics,18.42,High School,TUSTIN
24,A. J. Cook Elementary,Orange,Garden Grove Unified,92844,3,English Language Arts/Literacy,65.72,Elementary School,GARDEN GROVE
25,A. J. Cook Elementary,Orange,Garden Grove Unified,92844,3,Mathematics,79.28,Elementary School,GARDEN GROVE
26,A. J. Cook Elementary,Orange,Garden Grove Unified,92844,4,English Language Arts/Literacy,76.22,Elementary School,GARDEN GROVE
27,A. J. Cook Elementary,Orange,Garden Grove Unified,92844,4,Mathematics,81.81,Elementary School,GARDEN GROVE
28,A. J. Cook Elementary,Orange,Garden Grove Unified,92844,5,English Language Arts/Literacy,81.01,Elementary School,GARDEN GROVE
29,A. J. Cook Elementary,Orange,Garden Grove Unified,92844,5,Mathematics,66.35,Elementary School,GARDEN GROVE
...,...,...,...,...,...,...,...,...,...
77731,Zamorano Elementary,San Diego,San Diego Unified,92139,13,English Language Arts/Literacy,50.18,High School,SAN DIEGO
77732,Zamorano Elementary,San Diego,San Diego Unified,92139,13,Mathematics,41.27,High School,SAN DIEGO
77733,Zane Grey Continuation,Los Angeles,Los Angeles Unified,91335,11,Mathematics,0.00,High School,RESEDA
77734,Zane Grey Continuation,Los Angeles,Los Angeles Unified,91335,13,Mathematics,0.00,High School,RESEDA
77735,Zela Davis,Los Angeles,Hawthorne,90250,3,English Language Arts/Literacy,29.69,Elementary School,HAWTHORNE
77736,Zela Davis,Los Angeles,Hawthorne,90250,3,Mathematics,33.04,Elementary School,HAWTHORNE
77737,Zela Davis,Los Angeles,Hawthorne,90250,4,English Language Arts/Literacy,35.57,Elementary School,HAWTHORNE
77738,Zela Davis,Los Angeles,Hawthorne,90250,4,Mathematics,29.77,Elementary School,HAWTHORNE
77739,Zela Davis,Los Angeles,Hawthorne,90250,5,English Language Arts/Literacy,38.15,Elementary School,HAWTHORNE
77740,Zela Davis,Los Angeles,Hawthorne,90250,5,Mathematics,26.41,Elementary School,HAWTHORNE
77741,Zela Davis,Los Angeles,Hawthorne,90250,13,English Language Arts/Literacy,34.39,High School,HAWTHORNE
77742,Zela Davis,Los Angeles,Hawthorne,90250,13,Mathematics,29.73,High School,HAWTHORNE
77743,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,3,English Language Arts/Literacy,24.19,Elementary School,BAKERSFIELD
77744,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,3,Mathematics,24.79,Elementary School,BAKERSFIELD
77745,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,4,English Language Arts/Literacy,29.42,Elementary School,BAKERSFIELD
77746,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,4,Mathematics,16.99,Elementary School,BAKERSFIELD
77747,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,5,English Language Arts/Literacy,33.42,Elementary School,BAKERSFIELD
77748,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,5,Mathematics,14.45,Elementary School,BAKERSFIELD
77749,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,6,English Language Arts/Literacy,22.78,Elementary School,BAKERSFIELD
77750,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,6,Mathematics,16.12,Elementary School,BAKERSFIELD
77751,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,13,English Language Arts/Literacy,27.68,High School,BAKERSFIELD
77752,Zephyr Lane Elementary,Kern,Fairfax Elementary,93307,13,Mathematics,18.77,High School,BAKERSFIELD
77753,Zoe Barnum High,Humboldt,Eureka City Schools,95503,11,English Language Arts/Literacy,12.04,High School,EUREKA
77754,Zoe Barnum High,Humboldt,Eureka City Schools,95503,11,Mathematics,0.00,High School,EUREKA
77755,Zoe Barnum High,Humboldt,Eureka City Schools,95503,13,English Language Arts/Literacy,12.04,High School,EUREKA
77756,Zoe Barnum High,Humboldt,Eureka City Schools,95503,13,Mathematics,0.00,High School,EUREKA
77757,Zupanic High,San Bernardino,Rialto Unified,92376,11,English Language Arts/Literacy,21.25,High School,RIALTO
77758,Zupanic High,San Bernardino,Rialto Unified,92376,11,Mathematics,2.67,High School,RIALTO
77759,Zupanic High,San Bernardino,Rialto Unified,92376,13,English Language Arts/Literacy,21.25,High School,RIALTO
77760,Zupanic High,San Bernardino,Rialto Unified,92376,13,Mathematics,2.67,High School,RIALTO

In [23]:
data_summary.to_csv("School_Scores_Data_Summary.csv", index=False, header=True)